(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const css=document.createElement('style');css.textContent=`
.switch:checked{background:#27a844!important}.bonus-card{transition:.2s}.bonus-card.bonus-off{background:#efefef!important;border-color:#d5d5d5!important;color:#777}.bonus-card.bonus-off .bonus-meta,.bonus-card.bonus-off .field label{color:#999}.bonus-card.bonus-locked .bonus-controls,.bonus-card.bonus-locked .weekdays{opacity:.48}.bonus-lock{width:38px;height:38px;border:1.5px solid #181818;border-radius:12px;background:#fff;font-size:18px;display:grid;place-items:center;cursor:pointer;flex:none}.bonus-lock.locked{background:#f1eee7}.bonus-top{grid-template-columns:44px minmax(0,1fr) auto auto!important}.bonus-state-label{font-size:11px;font-weight:800;margin-top:3px}.bonus-state-label.on{color:#218838}.bonus-state-label.off{color:#888}.bonus-fixed-box{display:none!important}.redeem-hidden{display:none!important}.legacy-metric-hidden{display:none!important}
.metric-head{display:flex;align-items:center;gap:6px;margin-top:5px}.metric-head .label{margin-top:0}.info-btn{width:20px;height:20px;padding:0;border:1.5px solid #181818;border-radius:50%;background:#fff;color:#181818;font:800 12px/1 -apple-system,BlinkMacSystemFont,sans-serif;display:inline-grid;place-items:center;cursor:pointer;flex:none}.f-info{margin-left:5px;vertical-align:1px}.metric-pop{position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.28);display:grid;place-items:center;padding:20px}.metric-pop-card{width:min(390px,100%);background:#fff;border:2px solid #181818;border-radius:20px;padding:18px;box-shadow:4px 4px 0 #181818}.metric-pop-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.metric-pop-title{font-size:18px;font-weight:900}.metric-pop-text{font-size:14px;line-height:1.45;margin-top:9px;color:#444}.metric-pop-close{border:0;background:transparent;font-size:24px;line-height:1;cursor:pointer}.grid.metric-six{grid-template-columns:repeat(3,minmax(0,1fr))}
@media(max-width:850px){.grid.metric-six{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:480px){.bonus-top{grid-template-columns:42px minmax(0,1fr) auto auto!important}.bonus-lock{width:34px;height:34px}.info-btn{width:19px;height:19px;font-size:11px}}
`;document.head.appendChild(css);
const tips={
 devices:['Уникальные устройства','Количество разных устройств/браузеров, которые воспользовались механикой за выбранный период. Повторные действия одного устройства не увеличивают этот показатель.'],
 sessions:['Сессии','Количество отдельных посещений гостевой страницы. Одно устройство может создать несколько сессий, если возвращается позже.'],
 returning:['Вернувшиеся устройства','Сколько уникальных устройств уже бывали раньше и снова вернулись в выбранном периоде. Показывает повторный интерес к механике.'],
 perDevice:['Открытий на устройство','Среднее количество открытий печенья на одно уникальное устройство за выбранный период.'],
 opens:['Открытия печенья','Общее количество фактических открытий печенья за выбранный период. Одно устройство может дать несколько открытий, если правила это разрешают.'],
 menu:['Переходы на ресурс','Сколько раз гости нажали бизнес-кнопку и перешли на указанный ресурс: сайт, меню, каталог, акцию, Telegram и т. п.'],
 fVisited:['Зашли','Уникальные устройства, которые открыли гостевую страницу за выбранный период. Это начало воронки.'],
 fOpened:['Открыли','Уникальные устройства, которые дошли до открытия печенья. Процент показывает конверсию относительно предыдущего шага.'],
 fMenu:['Перешли на ресурс','Уникальные устройства, которые после взаимодействия нажали бизнес-кнопку и перешли на внешний ресурс.'],
 fBonus:['Получили бонус','Уникальные устройства, которым вместо обычного предсказания выпал настроенный бонус.']
};
function infoButton(key,extra=''){const t=tips[key];return t?`<button type="button" class="info-btn ${extra}" data-tip="${key}" aria-label="Что означает ${t[0]}" title="Что означает эта метрика">i</button>`:''}
function simplifyMetrics(){const grid=$('.grid');if(!grid||grid.dataset.metricsReady==='1')return;grid.dataset.metricsReady='1';grid.classList.add('metric-six');['views','again'].forEach(id=>$('#'+id)?.closest('.card')?.classList.add('legacy-metric-hidden'));const labels={devices:'Уникальные устройства',sessions:'Сессии',returning:'Вернувшиеся устройства',perDevice:'Открытий на устройство',opens:'Открытия печенья',menu:'Переходы на ресурс'};Object.entries(labels).forEach(([id,label])=>{const card=$('#'+id)?.closest('.card');if(!card)return;const old=card.querySelector('.label');if(old)old.remove();let head=card.querySelector('.metric-head');if(!head){head=document.createElement('div');head.className='metric-head';card.appendChild(head)}head.innerHTML=`<div class="label">${label}</div>${infoButton(id)}`})}
function explainFunnel(){const f=$('#funnel');if(!f)return;const steps=[...f.querySelectorAll('.fstep')].filter(x=>x.style.display!=='none');const keys=['fVisited','fOpened','fMenu','fBonus'];steps.forEach((step,i)=>{const b=step.querySelector('b');if(!b||!keys[i]||b.querySelector('.info-btn'))return;b.insertAdjacentHTML('beforeend',infoButton(keys[i],'f-info'))})}
let layoutDone=false;
function moveAnalytics(){if(layoutDone)return;const funnel=$('#funnel')?.closest('.panel');if(!funnel)return;const activity=$('#chart')?.closest('.panel');const events=$('#events')?.closest('.panel');if(activity&&funnel.nextElementSibling!==activity)funnel.insertAdjacentElement('afterend',activity);if(events&&activity&&activity.nextElementSibling!==events)activity.insertAdjacentElement('afterend',events);layoutDone=true}
function hideRedeem(){const fixed=$('.bonus-fixed-box');if(fixed)fixed.classList.add('redeem-hidden');const redeem=$('#redeemCode')?.closest('.formrow');if(redeem)redeem.classList.add('redeem-hidden');const claims=$('#claims');if(claims)claims.classList.add('redeem-hidden');const quick=$('#quickRedeem');if(quick)quick.classList.add('redeem-hidden');const funnel=$('#funnel');if(funnel){[...funnel.querySelectorAll('.fstep')].forEach(x=>{if(x.textContent.includes('Погасили'))x.style.display='none'})}}
function enhanceCard(card){if(!card||card.dataset.lockReady==='1')return;card.dataset.lockReady='1';const toggle=card.querySelector('.bonus-toggle');const del=card.querySelector('.bonus-delete');if(!toggle)return;const lock=document.createElement('button');lock.type='button';lock.className='bonus-lock locked';lock.setAttribute('aria-label','Разблокировать редактирование');lock.title='Разблокировать редактирование';lock.textContent='🔒';if(del)del.before(lock);else card.querySelector('.bonus-top')?.append(lock);const text=card.querySelector('.bonus-text');if(text){const state=document.createElement('div');state.className='bonus-state-label';text.insertAdjacentElement('afterend',state)}
const setLocked=locked=>{lock.classList.toggle('locked',locked);lock.textContent=locked?'🔒':'🔓';lock.title=locked?'Разблокировать редактирование':'Заблокировать редактирование';card.querySelectorAll('.bonus-field,.bonus-day').forEach(el=>el.disabled=locked);card.classList.toggle('bonus-locked',locked)};
const setActive=()=>{const on=toggle.checked;card.classList.toggle('bonus-off',!on);const state=card.querySelector('.bonus-state-label');if(state){state.textContent=on?'Бонус включён':'Бонус выключен';state.className='bonus-state-label '+(on?'on':'off')}};
setLocked(true);setActive();lock.addEventListener('click',()=>setLocked(!lock.classList.contains('locked')));toggle.addEventListener('change',()=>setTimeout(setActive,0));}
function openTip(key){const t=tips[key];if(!t)return;document.querySelector('.metric-pop')?.remove();const pop=document.createElement('div');pop.className='metric-pop';pop.innerHTML=`<div class="metric-pop-card" role="dialog" aria-modal="true"><div class="metric-pop-top"><div class="metric-pop-title">${t[0]}</div><button type="button" class="metric-pop-close" aria-label="Закрыть">×</button></div><div class="metric-pop-text">${t[1]}</div></div>`;document.body.appendChild(pop);pop.addEventListener('click',e=>{if(e.target===pop||e.target.closest('.metric-pop-close'))pop.remove()})}
document.addEventListener('click',e=>{const b=e.target.closest('.info-btn');if(b){e.preventDefault();e.stopPropagation();openTip(b.dataset.tip)}});
function enhanceAll(){simplifyMetrics();moveAnalytics();hideRedeem();explainFunnel();$$('.bonus-card').forEach(enhanceCard)}
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhanceAll()})};
const obs=new MutationObserver(schedule);
function init(){enhanceAll();obs.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,100));else setTimeout(init,100);
})();