(()=>{
const key='sb_publishable_KoG_6vK0nRhsnLntJf-TNA_4yXIAKo8';
const rpc='https://cneioixtqjncjzgtyhdk.supabase.co/rest/v1/rpc/add_bonus_campaign';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const style=document.createElement('style');style.textContent=`
.bonus-fixed-box,.bonus-create-box,.bonus-current-box{border:1.5px solid #d8d0c3;border-radius:16px;padding:14px;background:#faf8f2;margin:12px 0;min-width:0}
.bonus-fixed-box{background:#fff8d8;border-color:#181818}.bonus-fixed-box h3,.bonus-create-box h3,.bonus-current-box h3{margin:0 0 4px;font-size:16px}.bonus-section-note{font-size:12px;color:#777;margin-bottom:10px}.bonus-create-box[hidden]{display:none}.bonus-create-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:9px;margin-top:10px}.bonus-create-grid .field{min-width:0}.bonus-create-days{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.bonus-create-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.bonus-current-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;flex-wrap:wrap}.bonus-chance-explain{font-size:12px;color:#555}.bonus-chance-pill{background:#ffd61f;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:900}.bonus-add-main{width:100%;justify-content:center;margin:10px 0 0}.bonus-old-create{display:none!important}
@media(max-width:760px){.bonus-create-grid{grid-template-columns:1fr}.bonus-fixed-box,.bonus-create-box,.bonus-current-box{padding:12px}}
`;document.head.appendChild(style);
function build(){
 const panel=document.querySelector('[data-fold="bonuses"]'); if(!panel||panel.dataset.v14==='1')return;panel.dataset.v14='1';
 const body=panel.querySelector('.fold-body'); if(!body)return;
 const sectionHead=panel.querySelector('.section-head');
 const totalWrap=panel.querySelector('.bonus-total');
 const redeemInput=$('#redeemCode')?.closest('.formrow'); const claims=$('#claims'); const quick=$('#quickRedeem');
 const fixed=document.createElement('div');fixed.className='bonus-fixed-box';fixed.innerHTML='<h3>Погасить выигрыш</h3><div class="bonus-section-note">Этот блок всегда доступен. Введи код, который показывает гость.</div>';
 if(redeemInput)fixed.appendChild(redeemInput);if(claims)fixed.appendChild(claims);if(quick)quick.remove();
 if(sectionHead)sectionHead.insertAdjacentElement('afterend',fixed);else panel.prepend(fixed);
 const oldCreate=$('#bonusText')?.closest('.formrow'); if(oldCreate)oldCreate.classList.add('bonus-old-create'); const oldHelper=oldCreate?.nextElementSibling;if(oldHelper?.classList.contains('helper'))oldHelper.classList.add('bonus-old-create');
 const add=document.createElement('button');add.type='button';add.className='btn dark bonus-add-main';add.id='openBonusCreator';add.textContent='+ Добавить новый бонус';
 body.prepend(add);
 const create=document.createElement('div');create.className='bonus-create-box';create.id='bonusCreator';create.hidden=true;create.innerHTML=`<h3>Новый бонус</h3><div class="bonus-section-note">Здесь задаются все параметры будущей кампании. После сохранения бонус появится в списке ниже.</div><div class="bonus-create-grid"><div class="field"><label>Название / текст бонуса</label><input id="newBonusText" type="text" placeholder="Например: Скидка 50%"></div><div class="field"><label>Шанс выпадения на одно устройство, %</label><input id="newBonusProbability" type="number" min="0" max="100" step="0.1" value="1"></div><div class="field"><label>Всего бонусов за период, шт.</label><input id="newBonusMax" type="number" min="1" placeholder="Например, 100"></div><div class="field"><label>Период: с</label><input id="newBonusStart" type="datetime-local"></div><div class="field"><label>Период: по</label><input id="newBonusEnd" type="datetime-local"></div><div class="field"><label>Каждый день с</label><input id="newBonusStartTime" type="time"></div><div class="field"><label>Каждый день до</label><input id="newBonusEndTime" type="time"></div></div><div class="bonus-create-days"><b style="width:100%;font-size:12px">Дни недели</b>${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((n,i)=>`<label class="day"><input class="new-bonus-day" type="checkbox" value="${i+1}" checked>${n}</label>`).join('')}</div><div class="bonus-create-actions"><button type="button" class="btn dark" id="saveNewBonus">Создать бонус</button><button type="button" class="btn" id="cancelNewBonus">Отмена</button><span class="status" id="newBonusStatus"></span></div>`;
 add.insertAdjacentElement('afterend',create);
 const list=$('#bonusList'); if(list){const current=document.createElement('div');current.className='bonus-current-box';current.innerHTML='<div class="bonus-current-head"><div><h3>Текущие бонусы</h3><div class="bonus-chance-explain">Общий шанс — это сумма вероятностей всех включённых бонусов. Например, 2% + 3% = 5% шанс получить любой бонус вместо обычного предсказания.</div></div></div>';const head=current.querySelector('.bonus-current-head');if(totalWrap){totalWrap.className='bonus-chance-pill';totalWrap.innerHTML='Общий шанс получить бонус: <span id="bonusTotal">0</span>%';head.appendChild(totalWrap)}list.parentNode.insertBefore(current,list);current.appendChild(list)}
 const fold=panel.querySelector('[data-fold-toggle="bonuses"]');if(fold)fold.textContent=panel.classList.contains('expanded')?'Свернуть список бонусов':'Развернуть список бонусов';
}
async function save(){const st=$('#newBonusStatus'),text=$('#newBonusText')?.value.trim(),prob=Number($('#newBonusProbability')?.value||0),max=$('#newBonusMax')?.value,start=$('#newBonusStart')?.value,end=$('#newBonusEnd')?.value,startTime=$('#newBonusStartTime')?.value,endTime=$('#newBonusEndTime')?.value,days=$$('.new-bonus-day:checked').map(x=>Number(x.value));if(!text){st.textContent='Напиши название бонуса';st.className='status bad';return}if(prob<0||prob>100){st.textContent='Вероятность должна быть от 0 до 100%';st.className='status bad';return}if(max!==''&&Number(max)<=0){st.textContent='Количество бонусов должно быть больше нуля';st.className='status bad';return}st.textContent='Сохраняю…';st.className='status';const body={p_text:text,p_probability:prob,p_max_issues:max===''?null:Number(max),p_starts_at:start?new Date(start).toISOString():null,p_ends_at:end?new Date(end).toISOString():null,p_weekdays:days,p_start_time:startTime||null,p_end_time:endTime||null};try{const r=await fetch(rpc,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());st.textContent='Бонус создан';st.className='status good';setTimeout(()=>location.reload(),400)}catch(e){console.error(e);st.textContent='Не удалось создать бонус';st.className='status bad'}}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='openBonusCreator'){const c=$('#bonusCreator');c.hidden=false;t.hidden=true;c.scrollIntoView({behavior:'smooth',block:'nearest'})}if(t.id==='cancelNewBonus'){const c=$('#bonusCreator');c.hidden=true;$('#openBonusCreator').hidden=false}if(t.id==='saveNewBonus')save()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(build,50);bind()});else{setTimeout(build,50);bind()}
})();