(()=>{
const endpoint='https://cneioixtqjncjzgtyhdk.supabase.co/functions/v1/shurum-api';
const rest='https://cneioixtqjncjzgtyhdk.supabase.co/rest/v1/rpc/save_business_scenario';
const apiKey='sb_publishable_KoG_6vK0nRhsnLntJf-TNA_4yXIAKo8';
let days=7,syncing=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const short=s=>s?String(s).slice(0,8):'—';
const names={page_view:'Заход',fortune_opened:'Открыл печенье',fortune_again:'Ещё предсказание',menu_click:'Перешёл в ресурс',restart:'Начал заново',page_leave:'Вышел со страницы'};
const wd=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const post=async body=>{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){const e=new Error(d?.error||`HTTP ${r.status}`);e.data=d;throw e}return d};
const saveNamedScenario=async name=>{const r=await fetch(rest,{method:'POST',headers:{apikey:apiKey,'Content-Type':'application/json'},body:JSON.stringify({p_name:name})});const d=await r.json();if(!r.ok)throw new Error(d?.message||'scenario_save_failed');return d};
const dt=v=>v?new Date(v).toISOString().slice(0,16):'',fmt=v=>v?new Date(v).toLocaleString('ru-RU'):'—',fmtShort=v=>v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';

function prepareUI(){
  const bonusPanel=$('[data-fold="bonuses"] .fold-body');
  if(bonusPanel){
    const redeemInput=$('#redeemCode')?.closest('.formrow');
    const claims=$('#claims');
    if(redeemInput&&claims){
      const oldTitle=redeemInput.previousElementSibling;
      const quick=document.createElement('div');quick.id='quickRedeem';quick.innerHTML='<div><b>Быстро погасить выигрыш</b><div class="sub">Код гостя можно погасить сразу здесь — список бонусов ниже листать не нужно.</div></div>';
      bonusPanel.prepend(claims);bonusPanel.prepend(redeemInput);bonusPanel.prepend(quick);
      if(oldTitle&&oldTitle.textContent.includes('Погашение')) oldTitle.remove();
      const hr=[...bonusPanel.querySelectorAll('hr')][0]; if(hr)hr.remove();
    }
    const h=bonusPanel.parentElement?.querySelector('.sub');if(h)h.textContent='Каждый бонус — отдельная кампания: период, общий тираж, шанс выпадения на устройство и остаток.';
    const helper=bonusPanel.querySelector('.helper');if(helper)helper.textContent='При добавлении: текст бонуса · шанс выпадения на одно устройство, % · общий тираж бонусов за период. Пустой тираж = без ограничения.';
    const max=$('#bonusMax');if(max)max.placeholder='Всего шт.';
  }
  const sc=$('[data-fold="scenarios"] .fold-body');
  if(sc){
    const presets=$('#scenarioPresets');if(presets)presets.remove();
    let input=$('#scenarioName');
    if(!input){const row=document.createElement('div');row.className='formrow';row.innerHTML='<input id="scenarioName" type="text" placeholder="Например: Пятничный вечер" style="min-width:260px;flex:1"><button class="btn dark" id="saveScenarioNamed">Сохранить сценарий</button><span class="status" id="scenarioStatusNamed"></span>';sc.prepend(row);input=$('#scenarioName')}
    const old=$('#saveScenario')?.closest('.formrow');if(old)old.remove();
    const sub=sc.parentElement?.querySelector('.sub');if(sub)sub.textContent='Назови сценарий как удобно. В него сохранятся текущие бонусы, вероятности, тиражи, периоды, ограничения и кнопка.';
  }
}

function chart(daily=[]){const box=$('#chart');if(!box)return;if(!daily.length){box.innerHTML='<div class="chart-empty">Пока нет данных</div>';return}const vals=daily.map(x=>Number(x.opens)||0),max=Math.max(1,...vals),w=900,h=200,p=24,step=daily.length>1?(w-p*2)/(daily.length-1):0,pts=vals.map((v,i)=>[p+i*step,h-p-(v/max)*(h-p*2)]),path=pts.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' '),dots=pts.map((q,i)=>`<circle cx="${q[0]}" cy="${q[1]}" r="4" fill="#181818"><title>${esc(daily[i].day)}: ${vals[i]}</title></circle>`).join('');box.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#ddd"/><path d="${path}" fill="none" stroke="#181818" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>${dots}</svg>`}
function renderFunnel(f={}){const a=[['Зашли',f.visited||0],['Открыли',f.opened||0],['Перешли',f.menu||0],['Получили бонус',f.bonus||0],['Погасили',f.redeemed||0]];$('#funnel').innerHTML=a.map((x,i)=>{const prev=i?a[i-1][1]:0,p=i?(prev?Math.round(x[1]/prev*100):0):100;return `<div class="fstep"><div class="fnum">${x[1]}</div><b>${x[0]}</b><div class="fpct">${i?`${p}% от прошлого шага`:'100% входа'}</div></div>`}).join('')}
function renderEvents(ev=[]){$('#eventCount').textContent=`${ev.length} событий`;$('#events').innerHTML=ev.length?`<div class="events-list">${ev.map(e=>`<div class="event-row"><div class="ev-time event-meta">${fmtShort(e.created_at)}</div><div class="ev-device"><div class="event-meta">Устройство</div><b>${esc(short(e.device_id))}</b><div class="event-meta">Сессия ${esc(short(e.session_id))}</div></div><div class="ev-type"><div class="event-meta">Тип устройства</div>${esc([e.device_type,e.platform].filter(Boolean).join(' · ')||'—')}</div><div><div class="event-meta">Событие</div><b>${esc(names[e.type]||e.type||'—')}</b></div><div class="ev-content"><div class="event-meta">Содержимое</div>${esc(e.fortune_text||e.bonus_code||'—')}</div></div>`).join('')}</div>`:'<div class="empty">Пока нет событий за этот период.</div>'}
function renderFortunes(items=[]){$('#fortuneCount').textContent=`${items.filter(x=>x.active).length} включено · ${items.length} всего`;$('#fortuneList').innerHTML=items.length?items.map(x=>`<div class="fortune-item"><input class="switch fortune-toggle" type="checkbox" data-id="${x.id}" ${x.active?'checked':''}><div>${esc(x.text)}</div><button class="delete fortune-delete" data-id="${x.id}">×</button></div>`).join(''):'<div class="empty">Нет предсказаний.</div>'}
function renderBonuses(items=[]){const active=items.filter(x=>x.active),total=active.reduce((s,x)=>s+Number(x.probability||0),0);$('#bonusTotal').textContent=total.toFixed(total%1?1:0);$('#bonusTotal').parentElement.classList.toggle('danger',total>100);$('#bonusList').innerHTML=items.length?items.map((x,i)=>{const ds=(x.weekdays||[1,2,3,4,5,6,7]).map(Number),issued=Number(x.issued_total||0),period=x.starts_at||x.ends_at?`${x.starts_at?new Date(x.starts_at).toLocaleDateString('ru-RU'):'сейчас'} — ${x.ends_at?new Date(x.ends_at).toLocaleDateString('ru-RU'):'без окончания'}`:'без ограничения по датам';return `<div class="bonus-card"><div class="bonus-top"><input class="switch bonus-toggle" type="checkbox" data-id="${x.id}" ${x.active?'checked':''}><div><div class="bonus-text">${esc(x.text)}</div><div class="bonus-meta">Кампания: ${period} · шанс на устройство <b>${Number(x.probability)}%</b> · ${x.max_issues==null?'тираж без лимита':`тираж ${x.max_issues} шт. · выдано ${issued} · осталось ${x.remaining}`}</div></div><button class="delete bonus-delete" data-id="${x.id}">×</button></div><div class="bonus-controls"><div class="field"><label>Название / текст бонуса</label><input class="bonus-field" data-id="${x.id}" data-field="text" value="${esc(x.text)}"></div><div class="field"><label>Шанс на одно устройство, %</label><input class="bonus-field" data-id="${x.id}" data-field="probability" type="number" min="0" max="100" step="0.1" value="${Number(x.probability)}"></div><div class="field"><label>Всего бонусов за период, шт.</label><input class="bonus-field" data-id="${x.id}" data-field="max_issues" type="number" min="0" placeholder="∞" value="${x.max_issues??''}"></div><div class="field"><label>Период: с</label><input class="bonus-field" data-id="${x.id}" data-field="starts_at" type="datetime-local" value="${dt(x.starts_at)}"></div><div class="field"><label>Период: по</label><input class="bonus-field" data-id="${x.id}" data-field="ends_at" type="datetime-local" value="${dt(x.ends_at)}"></div><div class="field"><label>Каждый день с</label><input class="bonus-field" data-id="${x.id}" data-field="start_time" type="time" value="${x.start_time?String(x.start_time).slice(0,5):''}"></div><div class="field"><label>Каждый день до</label><input class="bonus-field" data-id="${x.id}" data-field="end_time" type="time" value="${x.end_time?String(x.end_time).slice(0,5):''}"></div></div><div class="weekdays">${wd.map((n,j)=>`<label class="day"><input class="bonus-day" data-id="${x.id}" data-day="${j+1}" type="checkbox" ${ds.includes(j+1)?'checked':''}>${n}</label>`).join('')}</div></div>`}).join(''):'<div class="empty">Пока бонусов нет. Добавь первый.</div>'}
function renderClaims(items=[],bonuses=[]){const bm=new Map(bonuses.map(b=>[b.id,b.text]));$('#claims').innerHTML=items.length?'<div class="helper" style="margin:8px 0">Последние выигрыши</div>'+items.slice(0,8).map(c=>`<div class="claim"><div><span class="code">${esc(c.claim_code)}</span> <span>${esc(bm.get(c.bonus_id)||'Бонус')}</span></div><div class="${c.redeemed_at?'ok':''}">${c.redeemed_at?'Погашен':'Выдан'}</div><div class="claim-time sub">${fmt(c.redeemed_at||c.issued_at)}</div></div>`).join(''):'<div class="helper">Выигрышей за выбранный период пока нет.</div>'}
function bonusLine(b){const lim=b.max_issues==null?'без лимита':`${b.max_issues} шт.`,range=(b.starts_at||b.ends_at)?`${b.starts_at?new Date(b.starts_at).toLocaleDateString('ru-RU'):'сейчас'}–${b.ends_at?new Date(b.ends_at).toLocaleDateString('ru-RU'):'∞'}`:'без дат';return `«${b.text}» — ${Number(b.probability||0)}% на устройство · тираж ${lim} · ${range}`}
function scenarioSummaryHtml(s){const c=s.config||{},bs=Array.isArray(c.bonuses)?c.bonuses.filter(x=>x.active):[],fs=Array.isArray(c.fortunes)?c.fortunes.filter(x=>x.active).length:0,b=c.business||{},lim=Number(b.max_opens_per_device_per_day)||0;return `${bs.length?bs.map(x=>`<div>• ${esc(bonusLine(x))}</div>`).join(''):'<div>• Активных бонусов нет</div>'}<div>• Предсказания: ${fs} активных</div><div>• Открытия: ${lim?`${lim} на устройство в день`:'без ограничения'}</div><div>• Бонус на устройство: ${b.one_bonus_per_device?'не более одного':'без ограничения'}</div><div>• Кнопка: «${esc(b.button_label||'ЗАГЛЯНУТЬ В МЕНЮ')}»</div>`}
function renderScenarios(items=[]){$('#scenarioList').innerHTML=items.length?items.map(s=>`<div class="scenario"><div><div class="row" style="justify-content:flex-start"><input class="switch scenario-toggle" type="checkbox" data-id="${s.id}" ${s.enabled?'checked':''}><b>${esc(s.name)}</b>${s.active?'<span class="badge active">сейчас применяется</span>':s.enabled?'<span class="badge yellow">включён</span>':''}</div><div class="scenario-summary">${scenarioSummaryHtml(s)}</div></div><div class="row"><button class="btn small scenario-apply" data-id="${s.id}">Применить сейчас</button><button class="btn small warn scenario-delete" data-id="${s.id}">Удалить</button></div></div>`).join(''):'<div class="helper">Сценариев пока нет. Настрой механику выше, придумай название и сохрани.</div>'}
function setInputs(c={}){if(document.activeElement!==$('#menuUrl'))$('#menuUrl').value=c.menu_url||'';if(document.activeElement!==$('#buttonLabel'))$('#buttonLabel').value=c.button_label||'ЗАГЛЯНУТЬ В МЕНЮ';if(document.activeElement!==$('#maxOpens'))$('#maxOpens').value=Number(c.max_opens_per_device_per_day)||0;$('#oneBonus').checked=!!c.one_bonus_per_device}
async function syncDefaultsIfNeeded(items){if(syncing||items.length>=50)return;syncing=true;try{const t=await fetch('https://shurum-burum-predskazanie.vercel.app/script.js').then(r=>r.text()),m=t.match(/const fortunes = (\[[\s\S]*?\]);/);if(m){const arr=Function(`"use strict";return (${m[1]})`)();if(Array.isArray(arr)&&arr.length>items.length){await post({action:'sync_fortunes',items:arr});await load()}}}catch(e){}finally{syncing=false}}
async function load(){try{const data=await post({action:'admin_data',days}),d=data.dashboard||{};$('#devices').textContent=d.unique_devices??0;$('#sessions').textContent=d.sessions??0;$('#returning').textContent=d.returning_devices??0;$('#perDevice').textContent=d.avg_opens_per_device??0;$('#views').textContent=d.page_views??0;$('#opens').textContent=d.opens??0;$('#again').textContent=d.fortune_again??0;$('#menu').textContent=d.menu_clicks??0;renderFunnel(data.funnel||{});chart(d.daily||[]);renderEvents(data.event_rows||d.recent||[]);renderFortunes(data.fortunes||[]);renderBonuses(data.bonuses||[]);renderClaims(data.claims||[],data.bonuses||[]);renderScenarios(data.scenarios||[]);setInputs(data.config||{});syncDefaultsIfNeeded(data.fortunes||[])}catch(e){console.error(e);$('#events').innerHTML='<div class="empty">Не удалось загрузить статистику.</div>'}}
function setFold(name,expanded){const p=document.querySelector(`[data-fold="${name}"]`),b=document.querySelector(`[data-fold-toggle="${name}"]`);if(!p||!b)return;p.classList.toggle('expanded',expanded);p.classList.toggle('compact',!expanded);b.textContent=expanded?'Свернуть':'Развернуть';try{localStorage.setItem(`shurum_admin_fold_${name}`,expanded?'1':'0')}catch(_){}}
prepareUI();['bonuses','limits','scenarios','events','fortunes'].forEach(name=>{let ex=name==='bonuses';try{const v=localStorage.getItem(`shurum_admin_fold_${name}`);if(v!==null)ex=v==='1'}catch(_){}setFold(name,ex)});

document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.foldToggle){const n=t.dataset.foldToggle,p=document.querySelector(`[data-fold="${n}"]`);setFold(n,!p.classList.contains('expanded'));return}if(t.id==='saveScenarioNamed'){const input=$('#scenarioName'),s=$('#scenarioStatusNamed'),name=input.value.trim();if(!name){s.textContent='Напиши название';s.className='status bad';return}try{await saveNamedScenario(name);s.textContent=`«${name}» сохранён`;s.className='status good';input.value='';load()}catch(_){s.textContent='Не удалось сохранить';s.className='status bad'}return}if(t.classList.contains('fortune-delete')&&confirm('Удалить это предсказание?')){await post({action:'fortune_delete',id:+t.dataset.id});load()}if(t.classList.contains('bonus-delete')&&confirm('Удалить этот бонус?')){await post({action:'bonus_delete',id:+t.dataset.id});load()}if(t.classList.contains('scenario-apply')){await post({action:'scenario_apply',id:+t.dataset.id});load()}if(t.classList.contains('scenario-delete')&&confirm('Удалить сценарий?')){await post({action:'scenario_delete',id:+t.dataset.id});load()}});
$$('[data-days]').forEach(b=>b.onclick=()=>{days=+b.dataset.days;$$('[data-days]').forEach(x=>x.classList.toggle('on',x===b));load()});
$('#addFortune').onclick=async()=>{const text=$('#fortuneText').value.trim();if(!text)return;await post({action:'fortune_add',text});$('#fortuneText').value='';load()};
$('#addBonus').onclick=async()=>{const text=$('#bonusText').value.trim(),probability=Number($('#bonusProb').value)||0,max=$('#bonusMax').value;if(!text)return;await post({action:'bonus_add',text,probability,max_issues:max===''?null:Number(max)});$('#bonusText').value='';$('#bonusMax').value='';load()};
$('#saveResource').onclick=async()=>{const s=$('#resourceStatus');try{await post({action:'config_update',menu_url:$('#menuUrl').value.trim(),button_label:$('#buttonLabel').value.trim()});s.textContent='Сохранено';s.className='status good';load()}catch(_){s.textContent='Не удалось сохранить';s.className='status bad'}};
$('#saveLimits').onclick=async()=>{const s=$('#limitsStatus');try{await post({action:'config_update',max_opens_per_device_per_day:Number($('#maxOpens').value)||0,one_bonus_per_device:$('#oneBonus').checked});s.textContent='Сохранено';s.className='status good';load()}catch(_){s.textContent='Не удалось сохранить';s.className='status bad'}};
$('#redeemBtn').onclick=async()=>{const s=$('#redeemStatus'),code=$('#redeemCode').value.trim();if(!code)return;try{const r=await post({action:'redeem',code});s.textContent=r.already?`Уже погашен: ${fmt(r.redeemed_at)}`:'Готово — бонус погашен';s.className=r.already?'status bad':'status good';if(!r.already)$('#redeemCode').value='';load()}catch(e){s.textContent=e.data?.error==='not_found'?'Такой код не найден':'Ошибка погашения';s.className='status bad'}};
document.addEventListener('change',async e=>{const t=e.target;if(t.classList.contains('scenario-toggle')){await post({action:'scenario_toggle',id:+t.dataset.id,enabled:t.checked});load();return}if(t.classList.contains('fortune-toggle')){await post({action:'fortune_toggle',id:+t.dataset.id,active:t.checked});load();return}if(t.classList.contains('bonus-toggle')){await post({action:'bonus_update',id:+t.dataset.id,active:t.checked});load();return}if(t.classList.contains('bonus-day')){const id=+t.dataset.id,ds=$$(`.bonus-day[data-id="${id}"]:checked`).map(x=>+x.dataset.day);await post({action:'bonus_update',id,weekdays:ds});load();return}if(t.classList.contains('bonus-field')){let v=t.value,f=t.dataset.field;if(['probability','max_issues'].includes(f))v=v===''?null:Number(v);if(['starts_at','ends_at'].includes(f))v=v?new Date(v).toISOString():null;if(['start_time','end_time'].includes(f))v=v||null;await post({action:'bonus_update',id:+t.dataset.id,[f]:v});load()}});
load();setInterval(()=>{if(!document.hidden&&!document.querySelector('.bonus-field:focus')&&!document.querySelector('#menuUrl:focus')&&!document.querySelector('#buttonLabel:focus')&&!document.querySelector('#maxOpens:focus')&&!document.querySelector('#scenarioName:focus'))load()},12000);
})();