(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const css=document.createElement('style');css.textContent=`
.switch:checked{background:#27a844!important}.bonus-card{transition:.2s}.bonus-card.bonus-off{background:#efefef!important;border-color:#d5d5d5!important;color:#777}.bonus-card.bonus-off .bonus-meta,.bonus-card.bonus-off .field label{color:#999}.bonus-card.bonus-locked .bonus-controls,.bonus-card.bonus-locked .weekdays{opacity:.48}.bonus-lock{width:38px;height:38px;border:1.5px solid #181818;border-radius:12px;background:#fff;font-size:18px;display:grid;place-items:center;cursor:pointer;flex:none}.bonus-lock.locked{background:#f1eee7}.bonus-top{grid-template-columns:44px minmax(0,1fr) auto auto!important}.bonus-state-label{font-size:11px;font-weight:800;margin-top:3px}.bonus-state-label.on{color:#218838}.bonus-state-label.off{color:#888}.bonus-fixed-box{display:none!important}
@media(max-width:480px){.bonus-top{grid-template-columns:42px minmax(0,1fr) auto auto!important}.bonus-lock{width:34px;height:34px}}
`;document.head.appendChild(css);
let layoutDone=false;
function moveAnalytics(){if(layoutDone)return;const funnel=$('#funnel')?.closest('.panel');if(!funnel)return;const activity=$('#chart')?.closest('.panel');const events=$('#events')?.closest('.panel');if(activity&&funnel.nextElementSibling!==activity)funnel.insertAdjacentElement('afterend',activity);if(events&&activity&&activity.nextElementSibling!==events)activity.insertAdjacentElement('afterend',events);layoutDone=true}
function removeRedeem(){const fixed=$('.bonus-fixed-box');if(fixed)fixed.remove();const redeem=$('#redeemCode')?.closest('.formrow');if(redeem)redeem.remove();$('#claims')?.remove();$('#quickRedeem')?.remove();const funnel=$('#funnel');if(funnel){[...funnel.querySelectorAll('.fstep')].forEach(x=>{if(x.textContent.includes('Погасили'))x.remove()})}}
function enhanceCard(card){if(!card||card.dataset.lockReady==='1')return;card.dataset.lockReady='1';const toggle=card.querySelector('.bonus-toggle');const del=card.querySelector('.bonus-delete');if(!toggle)return;const lock=document.createElement('button');lock.type='button';lock.className='bonus-lock locked';lock.setAttribute('aria-label','Разблокировать редактирование');lock.title='Разблокировать редактирование';lock.textContent='🔒';if(del)del.before(lock);else card.querySelector('.bonus-top')?.append(lock);const text=card.querySelector('.bonus-text');if(text){const state=document.createElement('div');state.className='bonus-state-label';text.insertAdjacentElement('afterend',state)}
const setLocked=locked=>{lock.classList.toggle('locked',locked);lock.textContent=locked?'🔒':'🔓';lock.title=locked?'Разблокировать редактирование':'Заблокировать редактирование';card.querySelectorAll('.bonus-field,.bonus-day').forEach(el=>el.disabled=locked);card.classList.toggle('bonus-locked',locked)};
const setActive=()=>{const on=toggle.checked;card.classList.toggle('bonus-off',!on);const state=card.querySelector('.bonus-state-label');if(state){state.textContent=on?'Бонус включён':'Бонус выключен';state.className='bonus-state-label '+(on?'on':'off')}};
setLocked(true);setActive();lock.addEventListener('click',()=>setLocked(!lock.classList.contains('locked')));toggle.addEventListener('change',()=>setTimeout(setActive,0));}
function enhanceAll(){moveAnalytics();removeRedeem();$$('.bonus-card').forEach(enhanceCard)}
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhanceAll()})};
const obs=new MutationObserver(schedule);
function init(){enhanceAll();obs.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,100));else setTimeout(init,100);
})();